<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <SatelliteResourceLanguages>ru;en</SatelliteResourceLanguages>
    <AssemblyName>Connector.Desktop</AssemblyName>
    <RootNamespace>Connector.Desktop</RootNamespace>
    <Version>1.0.29</Version>
    <FileVersion>1.0.29.0</FileVersion>
    <AssemblyVersion>1.0.29.0</AssemblyVersion>
    <ApplicationIcon>Assets\structura_connector.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="dnlib" Version="4.4.0" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\structura_connector.ico" />
    <Resource Include="Assets\structura_logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="PatchSets\Tekla\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <Content Include="tools\git\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
    <Content Include="tools\awg\**\*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      <CopyToPublishDirectory>PreserveNewest</CopyToPublishDirectory>
    </Content>
  </ItemGroup>

</Project>
